# Generated by Django 3.0.6 on 2020-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("up_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(default=1, upload_to="gallery"),
            preserve_default=False,
        ),
    ]
